[project]
name = "expense-tracker-mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "SparshGoyalFlexilyticsAI", email = "sparsh.goyal@flexilytics.ai" }
]
requires-python = ">=3.14"
dependencies = [
    "claude>=0.4.11",
    "fastapi>=0.141.1",
    "fastmcp>=3.4.6",
    "httpx>=0.28.1",
    "itsdangerous>=2.2.0",
    "python-jose[cryptography]>=3.5.0",
    "requests>=2.34.2",
    "supabase>=2.31.0",
]

[project.scripts]
expense-tracker-mcp-server = "expense_tracker_mcp_server:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
